sampletable: 'config/sampletable.tsv'

patterns: 'config/rnaseq_patterns.yaml'

# Which key in the `references` dict below to use
organism: 'human'

# If not specified here, use the environment variable REFERENCES_DIR.
references_dir: 'references_data'
 
# See https://rnabio.org/module-09-appendix/0009/12/01/StrandSettings for more info.
stranded: 'fr-firststrand'     # for dUTP libraries
#         'fr-secondstrand'    # for ligation libraries
#         'fr-firststrand'     # for dUTP libraries
#         'unstranded'         # for libraries without strand specificity

aligner:
  index: 'star-twopass'
  tag: 'gencode-v28'

rrna:
  index: 'bowtie2'
  tag: 'rRNA'

gtf:
  tag: "gencode-v28"

salmon:
  tag: "gencode-v28"

kallisto:
  tag: "gencode-v28"

fastq_screen:
  - label: rRNA
    organism: human
    tag: rRNA

# merged_bigwigs:
#   control_pos:
#     pos:
#       - sample1
#       - sample2
#   treatment_all:
#     pos:
#       - sample3
#       - sample4
#     neg:
#       - sample3
#       - sample4

# See the reference config files in the top level of the repo,
# include/reference_configs, for inspiration for more species.

include_references:
  - '../../include/reference_configs/Homo_sapiens.yaml'
